-- seed.sql
-- Mock data from "ICID MOCK DATA.xlsx" (sheets: USER, Client, PROJECT,
-- Project_User, Project_Client, Report). Form_Template and Completed_Form
-- are intentionally not seeded yet.
--
-- users.uuid is generated by the database. The integer "UUID" values from the
-- spreadsheet are used only to correlate rows across sheets, via the
-- temporary user_map table below (dropped automatically at COMMIT).
--
-- Run after schema.sql:  psql -d icid -f seed.sql

BEGIN;

------------------------------------------------------------
-- CLIENTS
------------------------------------------------------------
INSERT INTO icid.clients (client_id, client_username, client_name, client_email, client_phone, client_role) VALUES
    ('C00001',  'Magnol_Eng', 'Magnol Engineering PC',        'Admin@magnoleng.pc',    '(718) 024-6888', 'Consultant'),
    ('C00002',  'Goorkan_PC', 'Goorkan Engineering PC',       'Info@goorkaneng.com',   '(973) 654-3210', 'Consultant'),
    ('GC00003', 'Benny_Bow',  'Benny Bowers Contracting Co.', 'Admin@bennybowers.com', '(212)6802024',   'Contractor');

------------------------------------------------------------
-- USERS (uuid auto-generated; map spreadsheet ID -> generated uuid)
------------------------------------------------------------
CREATE TEMP TABLE user_map (
    excel_id  INT PRIMARY KEY,
    uuid      UUID NOT NULL
) ON COMMIT DROP;

WITH src (excel_id, email, first_name, last_name, phone_number, client_id) AS (
    VALUES
        (1, 'KhanG@magnoleng.pc',        'Genghis', 'Khan', '(914) 345-6789', 'C00001'),
        (2, 'Nadir.shah@goorkaneng.com', 'Nadir',   'Shah', '(201) 987-6543', 'C00002'),
        (3, 'WoodB@magnoleng.pc',        'Bally',   'Wood', '(347) 518-1315', 'C00001')
),
ins AS (
    INSERT INTO icid.users (email, first_name, last_name, phone_number, client_id)
    SELECT email, first_name, last_name, phone_number, client_id
    FROM src
    ORDER BY excel_id
    RETURNING uuid, email
)
INSERT INTO user_map (excel_id, uuid)
SELECT src.excel_id, ins.uuid
FROM src
JOIN ins ON ins.email = src.email;

------------------------------------------------------------
-- PROJECTS
------------------------------------------------------------
INSERT INTO icid.projects (project_id, project_name, project_description, registration_code, borough, status) VALUES
    ('HWS0023', 'S/W Queens 2025',          'Installation of Curb, Sidewalk and Ped-Ramp Various locations Queens', '2024123457', 'Queens', 'Construction; Active'),
    ('SE384',   'Combine Sewer Queens 2025', 'Installation of Combine Sewer in Maspeth, Queens',                     '2024123456', 'Queens', 'Construction; Active');

------------------------------------------------------------
-- PROJECT_CLIENTS
------------------------------------------------------------
INSERT INTO icid.project_clients (project_id, client_id, client_role) VALUES
    ('HWS0023', 'C00001', 'Consultant'),
    ('HWS0023', 'C00002', 'Consultant'),
    ('SE384',   'C00002', 'Consultant');

------------------------------------------------------------
-- PROJECT_USERS (resolve spreadsheet user IDs to generated uuids)
------------------------------------------------------------
INSERT INTO icid.project_users (project_id, user_uuid, user_role)
SELECT src.project_id, m.uuid, src.user_role
FROM (VALUES
    ('HWS0023', 1, 'Inspector'),
    ('SE384',   2, 'Inspector'),
    ('HWS0023', 2, 'Inspector'),
    ('HWS0023', 3, 'CCL')
) AS src (project_id, excel_id, user_role)
JOIN user_map m ON m.excel_id = src.excel_id;

------------------------------------------------------------
-- REPORTS (resolve reporter to generated uuid)
------------------------------------------------------------
INSERT INTO icid.reports (report_id, reporter_uuid, project_id, report_date)
SELECT src.report_id, m.uuid, src.project_id, src.report_date::DATE
FROM (VALUES
    ('R1', 1, 'HWS0023', '2025-09-16'),
    ('R2', 2, 'HWS0023', '2025-09-16'),
    ('R3', 3, 'HWS0023', '2025-09-16')
) AS src (report_id, excel_id, project_id, report_date)
JOIN user_map m ON m.excel_id = src.excel_id;

COMMIT;
